<?php
$ver =$this->view->viewVer;
$verParam = "?v=".$ver;
if( ! isset($this->view->footerName)){
	$this->view->footerName = "";
}
?>
		<!-- Footer -->
		<footer id="footer">
			<div class="copyright"></div>
		</footer>
		
	</div><!-- #all -->
	
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

	</body>
	
</html>