CREATE TABLE content_item (
  content_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  content_type VARCHAR(32) NOT NULL,
  plan VARCHAR(64) NOT NULL DEFAULT 'paid',
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  publish_start_at DATETIME NULL,
  publish_end_at DATETIME NULL,
  sort_order INT NOT NULL DEFAULT 0,
  config_json TEXT NULL,
  memo TEXT NULL,
  del_flag TINYINT NOT NULL DEFAULT 0,
  upd_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  reg_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (content_id),
  KEY idx_content_item_status_publish (status, publish_start_at, publish_end_at),
  KEY idx_content_item_type (content_type),
  KEY idx_content_item_del_flag (del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE content_file (
  file_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  content_id BIGINT UNSIGNED NOT NULL,
  file_type VARCHAR(32) NOT NULL,
  code VARCHAR(255) NOT NULL,
  file_key VARCHAR(255) NOT NULL,
  storage_path VARCHAR(512) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  display_name VARCHAR(255) NULL,
  mime_type VARCHAR(128) NULL,
  file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
  suffix VARCHAR(128) NULL,
  cache_value VARCHAR(64) NULL,
  is_primary TINYINT NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  del_flag TINYINT NOT NULL DEFAULT 0,
  upd_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  reg_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (file_id),
  UNIQUE KEY uq_content_file_code (code),
  KEY idx_content_file_content_id (content_id),
  KEY idx_content_file_type (file_type),
  KEY idx_content_file_del_flag (del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
