<?php

$this->view->hideLoginInfo = true;
$this->load( $this->getViewPath() . "header.phtml" );

$videoUrl = "";

?>
  <style>
    body {
      margin: 0;
      background: #000;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }
    video {
      width: 100%;
      height: 100%;
      max-width: 100%;
      max-height: 100%;
      background: #000;
    }
  </style>

		<!-- Main -->
		<div id="main">
  <video controls playsinline>
    <source src="<?php $this->h->print($videoUrl); ?>" type="video/mp4">
    お使いのブラウザは video タグをサポートしていません。
  </video>
		</div>
<?php

$this->load( $this->getViewPath() . "footer.phtml" );

?>
